server:
  port: 9000

spring:
  cloud:
    gateway:
      routes:
        # [N]:resilience]:circuit - Applies to the following restaurant-route definition which contains path to the Restaurant Microservice and a fallback uri
        - id: restaurant-route
          uri: http://localhost:9001/restaurants
          predicates:
            - Path=/restaurants/**
          filters:
            # [N]:resilience]:circuit
            - name: CircuitBreaker
              args:
                name: restaurantCircuitBreaker
                # See FallbackConfiguration
                fallbackUri: forward:/restaurant-fallback

management:
  endpoints:
    web:
      exposure:
        include: "*"

  redis:
    connect-timeout: 5s
    host: localhost
    port: 6379
    timeout: 500ms
    password:
  session:
    store-type: redis
    timeout: 10m
    redis:
      namespace: gulliver:gateway
