server:
  port: 8888

spring:
  profiles:
    active: vault
  cloud:
    config:
      server:
        vault:
          host: 192.168.0.127
          port: 8200
          kvVersion: 2
# logging:
#   level:
#     root: TRACE