server.port: 8888
spring:
  cloud:
    config:
      server:
        # [N]:config]:server]:git-repo - Tells Spring Cloud Config to use Git as a backend repository
        git:
          # [N]:git-repo - Tells Spring Cloud Config the URL to the Git server and repo
          uri: https://github.com/spring-petclinic/spring-petclinic-microservices-config
          default-label: main
        # [N]:config]:server]:file-repo - To avoid git pulling, you can tell Config Server to use your local Git repository in the File System Backend by using "native" Spring profile and setting "GIT_REPO" environment variable, for example: "-Dspring.profiles.active=native -DGIT_REPO=/projects/spring-petclinic-microservices-config".
        native:
          # [N]:config]:server]:file-repo - search-location: provides a comma-separated list of the directories for each application that will have properties managed by the Config Server. Here, the local configuration: can be either of classpath ...
          searchLocations: file:///${GIT_REPO}

